server.address=0.0.0.0
server.port=8086

#jwt.secret=Zs1YlH1J6Q2Wwtr1Fms0jdU7RvT6q6n5aTf9pJoXz3kKYZgUq0oS4jKs3EmUZFG1c61AjNDYuH+ucuhCV+YBXA==
jwt.secret=Zs1YlH1J6Q2Wwtr1Fms0jdU7RvT6q6n5aTf9pJoXz
jwt.expiration.hour=24


#spring.datasource.url=jdbc:postgresql://3.85.91.53:5444/fleetcore
#spring.datasource.url=jdbc:postgresql://34.207.65.178:5444/fleetcore
spring.datasource.url=jdbc:postgresql://192.168.100.251:5432/fleetcore
spring.datasource.username=enterprisedb
spring.datasource.password=adm123
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP Pool Configuration
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

# JPA Configuration and Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata


#Redis config
#spring.data.redis.host=192.168.100.251
#spring.data.redis.port=6379
#spring.data.redis.timeout=60000


# Optional: enable HikariCP debug logs to inspect pool behavior
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.jdbc.datasource=DEBUG
logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG

# Actuator
management.metrics.tags.application=Core-GPS-Tracking-System
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.endpoint.prometheus.enabled=true

management.health.diskspace.enabled=true
management.health.db.enabled=true