apiVersion: v1
kind: Service
metadata:
  name: intellifleet-core-api-service-01

spec:
  selector:
    app: intellifleet-core-api
  type: NodePort
  ports:
    - name: app-port
      port: 8086
      targetPort: 8086
      nodePort: 30086


