apiVersion: v1
kind: Service
metadata:
  name: intellifleet-core-api-service-01

spec:
  selector:
    app: intellifleet-core-api
  type: NodePort
  ports:
    - name: app-port
      port: 8084
      targetPort: 8084
      nodePort: 30084


